# CatBoost - Treinamento e Avaliação

In [2]:
# Instalação dos pacotes necessários
import sys
!{sys.executable} -m pip install catboost scikit-learn pandas numpy optuna

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: catboost in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (1.2.8)
Requirement already satisfied: scikit-learn in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (1.6.1)
Requirement already satisfied: pandas in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (1.26.4)
Requirement already satisfied: optuna in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (4.6.0)
Requirement already satisfied: scipy in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from catboost) (1.13.1)
Requirement already satisfied: graphviz in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from catboost) (0.21)
Requirement already satisfied: plotly in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from catboost) (6.5.0)
Requirement already satisfied: six in /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from catboost) (1.15.0)
Requirement already satisfied: matplotlib in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from catboost) (3.9.4)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: joblib>=1.2.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from pandas) (2025.2)
Requirement already satisfied: colorlog in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (6.10.1)
Requirement already satisfied: alembic>=1.5.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (1.16.5)
Requirement already satisfied: PyYAML in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (6.0.3)
Requirement already satisfied: packaging>=20.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (25.0)
Requirement already satisfied: tqdm in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (4.67.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from optuna) (1.4.40)
Requirement already satisfied: tomli in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (2.2.1)
Requirement already satisfied: typing-extensions>=4.12 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: Mako in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: MarkupSafe>=0.9.2 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Requirement already satisfied: importlib-resources>=3.2.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (6.5.2)
Requirement already satisfied: contourpy>=1.0.1 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.3.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: pyparsing>=2.3.1 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: pillow>=8 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from matplotlib->catboost) (1.4.7)
Requirement already satisfied: zipp>=3.1.0 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from importlib-resources>=3.2.0->matplotlib->catboost) (3.23.0)
Requirement already satisfied: narwhals>=1.15.1 in /Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages (from plotly->catboost) (2.13.0)
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip' command.

In [3]:
import os
import json
import time
import warnings
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, log_loss, roc_auc_score
from sklearn.model_selection import StratifiedKFold

from catboost import CatBoostClassifier
import optuna
from optuna.samplers import TPESampler

warnings.filterwarnings("ignore")
optuna.logging.set_verbosity(optuna.logging.WARNING)

SEED = 42

/Users/gabrielvanderlei/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Funções Auxiliares

In [4]:
def ensure_dirs():
    os.makedirs("trained_models_catboost", exist_ok=True)
    os.makedirs("results", exist_ok=True)
    os.makedirs("optuna_results", exist_ok=True)


def load_best_params(dataset_name: str):
    """Carrega hiperparâmetros do Optuna."""
    path = f"optuna_results/{dataset_name}_catboost_best.json"
    with open(path, "r") as f:
        data = json.load(f)
    return data["best_params"], data.get("tune_time", np.nan)


def load_dataset(dataset_name: str):
    """Carrega os datasets já separados."""
    train = pd.read_csv(f"train_datasets/{dataset_name}.csv")
    test = pd.read_csv(f"test_datasets/{dataset_name}.csv")
    return train, test

In [5]:
def preprocess(train_df: pd.DataFrame, test_df: pd.DataFrame):
    """Preprocessamento padronizado para treino e teste."""

    # Fit LabelEncoder no treino
    le_target = LabelEncoder()
    y_train = le_target.fit_transform(train_df["current_target_class"].values)
    y_test = le_target.transform(test_df["current_target_class"].values)

    cat_cols = train_df.select_dtypes(include="object").columns.tolist()
    num_cols = (
        train_df.select_dtypes(include=np.number)
        .drop(columns=["current_target_class"])
        .columns.tolist()
    )

    train_copy = train_df.copy()
    test_copy = test_df.copy()

    # Codificar categóricas
    cat_indices = []
    cat_encoders = {}

    if len(cat_cols) > 0:
        for c in cat_cols:
            enc = LabelEncoder()
            train_copy[c] = enc.fit_transform(train_copy[c].astype(str))

            # Handle unseen categories in test
            test_vals = test_copy[c].astype(str)
            test_copy[c] = test_vals.apply(
                lambda x: enc.transform([x])[0] if x in enc.classes_ else -1
            )
            cat_encoders[c] = enc

        cat_indices = list(range(len(num_cols), len(num_cols) + len(cat_cols)))

    # Features numéricas
    X_train_num = train_copy[num_cols].values.astype(np.float32)
    X_test_num = test_copy[num_cols].values.astype(np.float32)

    # Normalização
    scaler = StandardScaler()
    X_train_num = scaler.fit_transform(X_train_num)
    X_test_num = scaler.transform(X_test_num)

    # Concatenar
    if len(cat_cols) > 0:
        X_train_cat = train_copy[cat_cols].values.astype(np.int32)
        X_test_cat = test_copy[cat_cols].values.astype(np.int32)
        X_train = np.hstack([X_train_num, X_train_cat])
        X_test = np.hstack([X_test_num, X_test_cat])
    else:
        X_train = X_train_num
        X_test = X_test_num

    return X_train, X_test, y_train, y_test, cat_indices, le_target

## Métricas de Avaliação

In [6]:
def gmean_score(y_true, y_pred, eps=1e-9):
    """G-Mean: média geométrica dos recalls por classe."""
    classes = np.unique(y_true)
    recalls = []

    for c in classes:
        tp = np.sum((y_true == c) & (y_pred == c))
        fn = np.sum((y_true == c) & (y_pred != c))
        recalls.append(tp / (tp + fn + eps))

    return float(np.prod(recalls) ** (1.0 / len(recalls)))


def compute_auc_ovo(y_true, probs):
    """Cálculo robusto do AUC OVO."""
    y_true = np.asarray(y_true)
    probs = np.asarray(probs)
    unique_classes = np.unique(y_true)

    if len(unique_classes) < 2:
        return np.nan

    try:
        if len(unique_classes) > 2:
            return roc_auc_score(
                y_true,
                probs,
                multi_class="ovo",
                average="macro",
                labels=unique_classes
            )
        else:
            return roc_auc_score(y_true, probs[:, 1])
    except Exception:
        return np.nan


def evaluate_split(model, X, y):
    """Avaliação completa em um split (train/test)."""
    start = time.time()
    probs = model.predict_proba(X)
    tempo_predict = time.time() - start

    probs = np.asarray(probs)
    y = np.asarray(y)

    preds = np.argmax(probs, axis=1)

    return {
        "auc_ovo": compute_auc_ovo(y, probs),
        "mean_acc": accuracy_score(y, preds),
        "g_mean": gmean_score(y, preds),
        "mean_cross_entropy": log_loss(y, probs),
        "tempo_predict": tempo_predict,
    }

## Função de Treinamento

In [7]:
def train_final_model(dataset_name: str):
    """Treina modelo final com melhores hiperparâmetros."""
    print(f"\n{'='*60}")
    print(f"Treinando CatBoost para: {dataset_name}")
    print(f"{'='*60}")

    # Carregar melhores parâmetros
    best_params, tempo_tune = load_best_params(dataset_name)
    print(f"Melhores hiperparâmetros: {best_params}")

    # Carregar dados
    train_df, test_df = load_dataset(dataset_name)

    # Preprocessar
    X_train, X_test, y_train, y_test, cat_indices, le_target = preprocess(
        train_df, test_df
    )

    print(f"  Train: {X_train.shape[0]} amostras")
    print(f"  Test: {X_test.shape[0]} amostras")
    print(f"  Features: {X_train.shape[1]}")
    print(f"  Classes: {len(np.unique(y_train))}")

    # Configurar modelo
    model_params = {
        **best_params,
        "random_seed": SEED,
        "verbose": False,
        "thread_count": -1,
        "task_type": "CPU",
    }

    model = CatBoostClassifier(**model_params)

    # Treinar
    start_train = time.time()

    if len(cat_indices) > 0:
        model.fit(X_train, y_train, cat_features=cat_indices, verbose=False)
    else:
        model.fit(X_train, y_train, verbose=False)

    tempo_train = time.time() - start_train
    print(f"  Tempo de treino: {tempo_train:.2f}s")

    # Salvar modelo
    model_path = f"trained_models_catboost/{dataset_name}_catboost.cbm"
    model.save_model(model_path)
    print(f"  Modelo salvo: {model_path}")

    # Avaliar
    train_metrics = evaluate_split(model, X_train, y_train)
    test_metrics = evaluate_split(model, X_test, y_test)

    print(f"\n  Resultados no TREINO:")
    print(f"    AUC OVO: {train_metrics['auc_ovo']:.4f}")
    print(f"    Accuracy: {train_metrics['mean_acc']:.4f}")
    print(f"    G-Mean: {train_metrics['g_mean']:.4f}")
    print(f"    Cross-Entropy: {train_metrics['mean_cross_entropy']:.4f}")

    print(f"\n  Resultados no TESTE:")
    print(f"    AUC OVO: {test_metrics['auc_ovo']:.4f}")
    print(f"    Accuracy: {test_metrics['mean_acc']:.4f}")
    print(f"    G-Mean: {test_metrics['g_mean']:.4f}")
    print(f"    Cross-Entropy: {test_metrics['mean_cross_entropy']:.4f}")

    # Construir saída
    rows = []

    for split, metrics in [("train", train_metrics), ("test", test_metrics)]:
        rows.append({
            "split": split,
            "nome_modelo": "CatBoost",
            "dataset": dataset_name,
            "tempo_tune": tempo_tune,
            "tempo_train": tempo_train,
            "auc_ovo": metrics["auc_ovo"],
            "mean_acc": metrics["mean_acc"],
            "g_mean": metrics["g_mean"],
            "mean_cross_entropy": metrics["mean_cross_entropy"],
            "tempo_predict": metrics["tempo_predict"],
        })

    return rows

## Otimização de Hiperparâmetros (Tuning)

In [8]:
def tune_catboost_optuna(dataset_name: str, n_trials: int = 50):
    """
    Otimiza hiperparâmetros do CatBoost usando Optuna com validação cruzada.
    """
    print(f"\n{'='*60}")
    print(f"Tuning CatBoost para: {dataset_name}")
    print(f"{'='*60}")
    
    # Carregar dados
    train_df, test_df = load_dataset(dataset_name)
    
    # Preprocessar
    X_train, X_test, y_train, y_test, cat_indices, le_target = preprocess(
        train_df, test_df
    )
    
    print(f"  Train: {X_train.shape[0]} amostras")
    print(f"  Features: {X_train.shape[1]}")
    print(f"  Classes: {len(np.unique(y_train))}")
    print(f"  Trials: {n_trials}")
    
    # Função objetivo para o Optuna
    def objective(trial):
        params = {
            "iterations": trial.suggest_int("iterations", 50, 500),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "depth": trial.suggest_int("depth", 3, 10),
            "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-2, 10.0, log=True),
            "random_strength": trial.suggest_float("random_strength", 1e-3, 10.0, log=True),
            "bagging_temperature": trial.suggest_float("bagging_temperature", 0.0, 1.0),
            "border_count": trial.suggest_int("border_count", 32, 255),
            "random_seed": SEED,
            "verbose": False,
            "thread_count": -1,
            "task_type": "CPU",
        }
        
        # Validação cruzada estratificada
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
        cv_scores = []
        
        for train_idx, val_idx in skf.split(X_train, y_train):
            X_tr, X_val = X_train[train_idx], X_train[val_idx]
            y_tr, y_val = y_train[train_idx], y_train[val_idx]
            
            model = CatBoostClassifier(**params)
            
            if len(cat_indices) > 0:
                model.fit(X_tr, y_tr, cat_features=cat_indices, verbose=False)
            else:
                model.fit(X_tr, y_tr, verbose=False)
            
            probs = model.predict_proba(X_val)
            auc = compute_auc_ovo(y_val, probs)
            
            if not np.isnan(auc):
                cv_scores.append(auc)
        
        return np.mean(cv_scores) if len(cv_scores) > 0 else 0.0
    
    # Executar otimização
    start_time = time.time()
    
    study = optuna.create_study(
        direction="maximize",
        sampler=TPESampler(seed=SEED)
    )
    
    study.optimize(objective, n_trials=n_trials, show_progress_bar=True)
    
    tune_time = time.time() - start_time
    
    # Melhores parâmetros
    best_params = study.best_params
    best_score = study.best_value
    
    print(f"\n  Melhor AUC (CV): {best_score:.4f}")
    print(f"  Tempo de tuning: {tune_time:.2f}s")
    print(f"  Melhores parâmetros: {best_params}")
    
    # Salvar resultados
    output = {
        "dataset": dataset_name,
        "best_params": best_params,
        "best_score": float(best_score),
        "tune_time": float(tune_time),
        "n_trials": n_trials,
    }
    
    output_path = f"optuna_results/{dataset_name}_catboost_best.json"
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)
    
    print(f"  Resultados salvos: {output_path}")
    
    return best_params, best_score, tune_time

In [9]:
# EXECUTAR TUNING PARA TODOS OS DATASETS
# Execute esta célula apenas se quiser rodar o tuning manualmente
# Os resultados são salvos em optuna_results/ e reutilizados automaticamente

ensure_dirs()

# Lista completa dos 30 datasets
dataset_list_tune = [
    # Datasets balanceados
    'credit-approval', 'dresses-sales', 'mfeat-morphological', 'vehicle',
    'banknote-authentication', 'analcatdata_dmft', 'MiceProtein', 'cylinder-bands',
    'semeion', 'cnae-9', 'vowel',
    # Datasets desbalanceados
    'breast-w', 'eucalyptus', 'wdbc', 'pc4', 'credit-g', 'cmc',
    'blood-transfusion-service-center', 'pc3', 'car', 'kc2',
    'steel-plates-fault', 'balance-scale', 'pc1', 'tic-tac-toe',
    'analcatdata_authorship', 'climate-model-simulation-crashes',
    'qsar-biodeg', 'diabetes', 'ilpd',
]

# Executar tuning para cada dataset
tune_results = []

for ds in dataset_list_tune:
    try:
        # Verificar se já foi tunado
        param_path = f"optuna_results/{ds}_catboost_best.json"
        
        if os.path.exists(param_path):
            print(f"\n[INFO] {ds} já foi tunado. Pulando...")
            # Carregar resultados existentes
            with open(param_path, 'r') as f:
                data = json.load(f)
                tune_results.append({
                    'dataset': ds,
                    'best_score': data['best_score'],
                    'tune_time': data['tune_time']
                })
        else:
            print(f"\n[INFO] Tunando {ds}...")
            best_params, best_score, tune_time = tune_catboost_optuna(ds, n_trials=50)
            tune_results.append({
                'dataset': ds,
                'best_score': best_score,
                'tune_time': tune_time
            })
    except Exception as e:
        print(f"\n[ERRO] Dataset {ds}: {e}")
        continue

# Resumo dos resultados de tuning
if len(tune_results) > 0:
    tune_df = pd.DataFrame(tune_results)
    print(f"\n{'='*60}")
    print("RESUMO DO TUNING")
    print(f"{'='*60}")
    print(f"Total de datasets: {len(tune_df)}")
    print(f"Tempo total de tuning: {tune_df['tune_time'].sum():.2f}s")
    print(f"AUC médio (CV): {tune_df['best_score'].mean():.4f}")
    display(tune_df.sort_values('best_score', ascending=False))

[INFO] credit-approval já foi tunado. Pulando...

[INFO] dresses-sales já foi tunado. Pulando...

[INFO] mfeat-morphological já foi tunado. Pulando...

[INFO] vehicle já foi tunado. Pulando...

[INFO] banknote-authentication já foi tunado. Pulando...

[INFO] analcatdata_dmft já foi tunado. Pulando...

[INFO] MiceProtein já foi tunado. Pulando...

[INFO] cylinder-bands já foi tunado. Pulando...

[INFO] Tunando semeion...

============================================================
Tuning CatBoost para: semeion
============================================================
  Train: 1003 amostras
  Features: 256
  Classes: 10
  Trials: 50

Best trial: 32. Best value: 0.997293: 100%|██████████| 50/50 [59:12<00:00, 71.05s/it]

  Melhor AUC (CV): 0.9973
  Tempo de tuning: 3552.30s
  Melhores parâmetros: {'iterations': 433, 'learning_rate': 0.09109634495981846, 'depth': 4, 'l2_leaf_reg': 0.06283219021952564, 'random_strength': 0.006190558077203713, 'bagging_temperature': 0.03198201865774064, 'border_count': 32}
  Resultados salvos: optuna_results/semeion_catboost_best.json

[INFO] Tunando cnae-9...

============================================================
Tuning CatBoost para: cnae-9
============================================================
  Train: 680 amostras
  Features: 856
  Classes: 9
  Trials: 50

Best trial: 22. Best value: 0.995036: 100%|██████████| 50/50 [09:06<00:00, 10.93s/it]

  Melhor AUC (CV): 0.9950
  Tempo de tuning: 546.31s
  Melhores parâmetros: {'iterations': 452, 'learning_rate': 0.040359456141514524, 'depth': 10, 'l2_leaf_reg': 0.06035601781783563, 'random_strength': 3.2092601977965796, 'bagging_temperature': 0.838845022048059, 'border_count': 201}
  Resultados salvos: optuna_results/cnae-9_catboost_best.json

[INFO] Tunando vowel...

============================================================
Tuning CatBoost para: vowel
============================================================
  Train: 623 amostras
  Features: 12
  Classes: 11
  Trials: 50

Best trial: 1. Best value: 0.998535: 100%|██████████| 50/50 [06:42<00:00,  8.06s/it]

  Melhor AUC (CV): 0.9985
  Tempo de tuning: 402.98s
  Melhores parâmetros: {'iterations': 440, 'learning_rate': 0.07725378389307355, 'depth': 8, 'l2_leaf_reg': 0.011527987128232402, 'random_strength': 7.579479953348009, 'bagging_temperature': 0.8324426408004217, 'border_count': 79}
  Resultados salvos: optuna_results/vowel_catboost_best.json

[INFO] Tunando breast-w...

============================================================
Tuning CatBoost para: breast-w
============================================================
  Train: 440 amostras
  Features: 9
  Classes: 2
  Trials: 50

Best trial: 33. Best value: 0.994157: 100%|██████████| 50/50 [00:15<00:00,  3.23it/s]

  Melhor AUC (CV): 0.9942
  Tempo de tuning: 15.48s
  Melhores parâmetros: {'iterations': 473, 'learning_rate': 0.023596041097921166, 'depth': 3, 'l2_leaf_reg': 0.38472443810911483, 'random_strength': 1.8308510115244405, 'bagging_temperature': 0.29850342982695705, 'border_count': 62}
  Resultados salvos: optuna_results/breast-w_catboost_best.json

[INFO] Tunando eucalyptus...

============================================================
Tuning CatBoost para: eucalyptus
============================================================
  Train: 350 amostras
  Features: 19
  Classes: 4
  Trials: 50

Best trial: 34. Best value: 0.866198: 100%|██████████| 50/50 [00:46<00:00,  1.08it/s]

  Melhor AUC (CV): 0.8662
  Tempo de tuning: 46.16s
  Melhores parâmetros: {'iterations': 337, 'learning_rate': 0.04577423662995581, 'depth': 5, 'l2_leaf_reg': 3.445991322357863, 'random_strength': 2.734435746603416, 'bagging_temperature': 0.22316076445423746, 'border_count': 91}
  Resultados salvos: optuna_results/eucalyptus_catboost_best.json

[INFO] Tunando wdbc...

============================================================
Tuning CatBoost para: wdbc
============================================================
  Train: 358 amostras
  Features: 30
  Classes: 2
  Trials: 50

Best trial: 42. Best value: 0.991388: 100%|██████████| 50/50 [01:14<00:00,  1.50s/it]

  Melhor AUC (CV): 0.9914
  Tempo de tuning: 74.93s
  Melhores parâmetros: {'iterations': 197, 'learning_rate': 0.022194461001238907, 'depth': 8, 'l2_leaf_reg': 0.025506553470523986, 'random_strength': 5.137597547919509, 'bagging_temperature': 0.3107158525298094, 'border_count': 243}
  Resultados salvos: optuna_results/wdbc_catboost_best.json

[INFO] Tunando pc4...

============================================================
Tuning CatBoost para: pc4
============================================================
  Train: 918 amostras
  Features: 37
  Classes: 2
  Trials: 50

Best trial: 45. Best value: 0.94169: 100%|██████████| 50/50 [01:03<00:00,  1.28s/it]

  Melhor AUC (CV): 0.9417
  Tempo de tuning: 63.82s
  Melhores parâmetros: {'iterations': 220, 'learning_rate': 0.019195790953683137, 'depth': 7, 'l2_leaf_reg': 1.2192877487916944, 'random_strength': 0.03833083258575718, 'bagging_temperature': 0.2840087086504303, 'border_count': 34}
  Resultados salvos: optuna_results/pc4_catboost_best.json

[INFO] Tunando credit-g...

============================================================
Tuning CatBoost para: credit-g
============================================================
  Train: 630 amostras
  Features: 20
  Classes: 2
  Trials: 50

Best trial: 43. Best value: 0.770089: 100%|██████████| 50/50 [00:24<00:00,  2.01it/s]

  Melhor AUC (CV): 0.7701
  Tempo de tuning: 24.87s
  Melhores parâmetros: {'iterations': 284, 'learning_rate': 0.03082519278153801, 'depth': 6, 'l2_leaf_reg': 4.632954876006153, 'random_strength': 6.515438729889783, 'bagging_temperature': 0.8205248119201679, 'border_count': 46}
  Resultados salvos: optuna_results/credit-g_catboost_best.json

[INFO] Tunando cmc...

============================================================
Tuning CatBoost para: cmc
============================================================
  Train: 927 amostras
  Features: 9
  Classes: 3
  Trials: 50

Best trial: 23. Best value: 0.727396: 100%|██████████| 50/50 [00:22<00:00,  2.23it/s]

  Melhor AUC (CV): 0.7274
  Tempo de tuning: 22.45s
  Melhores parâmetros: {'iterations': 464, 'learning_rate': 0.015144096298459114, 'depth': 4, 'l2_leaf_reg': 9.864098940130239, 'random_strength': 0.01883520641442139, 'bagging_temperature': 0.2282974055610772, 'border_count': 165}
  Resultados salvos: optuna_results/cmc_catboost_best.json

[INFO] Tunando blood-transfusion-service-center...

============================================================
Tuning CatBoost para: blood-transfusion-service-center
============================================================
  Train: 470 amostras
  Features: 4
  Classes: 2
  Trials: 50

Best trial: 45. Best value: 0.757374: 100%|██████████| 50/50 [00:13<00:00,  3.76it/s]

  Melhor AUC (CV): 0.7574
  Tempo de tuning: 13.31s
  Melhores parâmetros: {'iterations': 186, 'learning_rate': 0.0241090156225405, 'depth': 3, 'l2_leaf_reg': 0.7906565859118585, 'random_strength': 4.9621912184240005, 'bagging_temperature': 0.701770768490543, 'border_count': 97}
  Resultados salvos: optuna_results/blood-transfusion-service-center_catboost_best.json

[INFO] Tunando pc3...

============================================================
Tuning CatBoost para: pc3
============================================================
  Train: 984 amostras
  Features: 37
  Classes: 2
  Trials: 50

Best trial: 41. Best value: 0.86155: 100%|██████████| 50/50 [01:07<00:00,  1.35s/it]

  Melhor AUC (CV): 0.8615
  Tempo de tuning: 67.74s
  Melhores parâmetros: {'iterations': 358, 'learning_rate': 0.01018158968177659, 'depth': 5, 'l2_leaf_reg': 0.012748802652224488, 'random_strength': 0.03031020779895982, 'bagging_temperature': 0.8841734109557197, 'border_count': 239}
  Resultados salvos: optuna_results/pc3_catboost_best.json

[INFO] Tunando car...

============================================================
Tuning CatBoost para: car
============================================================
  Train: 1088 amostras
  Features: 6
  Classes: 4
  Trials: 50

Best trial: 34. Best value: 0.999519: 100%|██████████| 50/50 [00:22<00:00,  2.23it/s]

  Melhor AUC (CV): 0.9995
  Tempo de tuning: 22.45s
  Melhores parâmetros: {'iterations': 182, 'learning_rate': 0.06931052352438204, 'depth': 6, 'l2_leaf_reg': 0.014987093363755994, 'random_strength': 0.0010354844596193377, 'bagging_temperature': 0.18764823680388093, 'border_count': 168}
  Resultados salvos: optuna_results/car_catboost_best.json

[INFO] Tunando kc2...

============================================================
Tuning CatBoost para: kc2
============================================================
  Train: 328 amostras
  Features: 21
  Classes: 2
  Trials: 50

Best trial: 49. Best value: 0.890777: 100%|██████████| 50/50 [01:14<00:00,  1.48s/it]

  Melhor AUC (CV): 0.8908
  Tempo de tuning: 74.22s
  Melhores parâmetros: {'iterations': 336, 'learning_rate': 0.024725432634456045, 'depth': 3, 'l2_leaf_reg': 3.5287603689687526, 'random_strength': 0.016280202637738, 'bagging_temperature': 0.8932078456752282, 'border_count': 243}
  Resultados salvos: optuna_results/kc2_catboost_best.json

[INFO] Tunando steel-plates-fault...

============================================================
Tuning CatBoost para: steel-plates-fault
============================================================
  Train: 1222 amostras
  Features: 27
  Classes: 7
  Trials: 50

Best trial: 48. Best value: 0.968284: 100%|██████████| 50/50 [04:49<00:00,  5.80s/it]

  Melhor AUC (CV): 0.9683
  Tempo de tuning: 289.92s
  Melhores parâmetros: {'iterations': 482, 'learning_rate': 0.11389744687452437, 'depth': 6, 'l2_leaf_reg': 2.0372703602990074, 'random_strength': 1.7713868448871888, 'bagging_temperature': 0.1848987975553109, 'border_count': 58}
  Resultados salvos: optuna_results/steel-plates-fault_catboost_best.json

[INFO] Tunando balance-scale...

============================================================
Tuning CatBoost para: balance-scale
============================================================
  Train: 393 amostras
  Features: 4
  Classes: 3
  Trials: 50

Best trial: 41. Best value: 0.953445: 100%|██████████| 50/50 [00:10<00:00,  4.84it/s]

  Melhor AUC (CV): 0.9534
  Tempo de tuning: 10.33s
  Melhores parâmetros: {'iterations': 363, 'learning_rate': 0.19002893624554873, 'depth': 4, 'l2_leaf_reg': 0.7875595671132296, 'random_strength': 0.007826811222696904, 'bagging_temperature': 0.3356874421657183, 'border_count': 119}
  Resultados salvos: optuna_results/balance-scale_catboost_best.json

[INFO] Tunando pc1...

============================================================
Tuning CatBoost para: pc1
============================================================
  Train: 698 amostras
  Features: 21
  Classes: 2
  Trials: 50

Best trial: 19. Best value: 0.880341: 100%|██████████| 50/50 [01:16<00:00,  1.53s/it]

  Melhor AUC (CV): 0.8803
  Tempo de tuning: 76.32s
  Melhores parâmetros: {'iterations': 174, 'learning_rate': 0.07934237918397923, 'depth': 10, 'l2_leaf_reg': 4.860114156580749, 'random_strength': 0.7329821378866582, 'bagging_temperature': 0.6826182661984666, 'border_count': 178}
  Resultados salvos: optuna_results/pc1_catboost_best.json

[INFO] Tunando tic-tac-toe...

============================================================
Tuning CatBoost para: tic-tac-toe
============================================================
  Train: 603 amostras
  Features: 9
  Classes: 2
  Trials: 50

Best trial: 14. Best value: 1: 100%|██████████| 50/50 [00:18<00:00,  2.67it/s]

  Melhor AUC (CV): 1.0000
  Tempo de tuning: 18.71s
  Melhores parâmetros: {'iterations': 343, 'learning_rate': 0.13999834028477615, 'depth': 6, 'l2_leaf_reg': 0.1214423851252321, 'random_strength': 0.29968948789610234, 'bagging_temperature': 0.7066027851795458, 'border_count': 195}
  Resultados salvos: optuna_results/tic-tac-toe_catboost_best.json

[INFO] Tunando analcatdata_authorship...

============================================================
Tuning CatBoost para: analcatdata_authorship
============================================================
  Train: 529 amostras
  Features: 70
  Classes: 4
  Trials: 50

Best trial: 41. Best value: 1: 100%|██████████| 50/50 [04:38<00:00,  5.57s/it]

  Melhor AUC (CV): 1.0000
  Tempo de tuning: 278.40s
  Melhores parâmetros: {'iterations': 461, 'learning_rate': 0.037138849888776686, 'depth': 9, 'l2_leaf_reg': 0.012516946208041318, 'random_strength': 7.697180747899158, 'bagging_temperature': 0.9961602315751977, 'border_count': 34}
  Resultados salvos: optuna_results/analcatdata_authorship_catboost_best.json

[INFO] Tunando climate-model-simulation-crashes...

============================================================
Tuning CatBoost para: climate-model-simulation-crashes
============================================================
  Train: 340 amostras
  Features: 18
  Classes: 2
  Trials: 50

Best trial: 32. Best value: 0.943963: 100%|██████████| 50/50 [00:47<00:00,  1.04it/s]

  Melhor AUC (CV): 0.9440
  Tempo de tuning: 47.89s
  Melhores parâmetros: {'iterations': 94, 'learning_rate': 0.024038564325496777, 'depth': 8, 'l2_leaf_reg': 0.7148984047579091, 'random_strength': 0.4657181661465716, 'bagging_temperature': 0.24770790248158484, 'border_count': 33}
  Resultados salvos: optuna_results/climate-model-simulation-crashes_catboost_best.json

[INFO] Tunando qsar-biodeg...

============================================================
Tuning CatBoost para: qsar-biodeg
============================================================
  Train: 664 amostras
  Features: 41
  Classes: 2
  Trials: 50

Best trial: 39. Best value: 0.915507: 100%|██████████| 50/50 [00:41<00:00,  1.20it/s]

  Melhor AUC (CV): 0.9155
  Tempo de tuning: 41.78s
  Melhores parâmetros: {'iterations': 383, 'learning_rate': 0.02017474009955968, 'depth': 6, 'l2_leaf_reg': 0.010094917202824297, 'random_strength': 5.933127554976763, 'bagging_temperature': 0.7551326567568609, 'border_count': 66}
  Resultados salvos: optuna_results/qsar-biodeg_catboost_best.json

[INFO] Tunando diabetes...

============================================================
Tuning CatBoost para: diabetes
============================================================
  Train: 483 amostras
  Features: 8
  Classes: 2
  Trials: 50

Best trial: 3. Best value: 0.839521: 100%|██████████| 50/50 [00:13<00:00,  3.60it/s]

  Melhor AUC (CV): 0.8395
  Tempo de tuning: 13.90s
  Melhores parâmetros: {'iterations': 112, 'learning_rate': 0.027010527749605478, 'depth': 5, 'l2_leaf_reg': 0.23345864076016243, 'random_strength': 1.382623217936987, 'bagging_temperature': 0.19967378215835974, 'border_count': 147}
  Resultados salvos: optuna_results/diabetes_catboost_best.json

[INFO] Tunando ilpd...

============================================================
Tuning CatBoost para: ilpd
============================================================
  Train: 367 amostras
  Features: 10
  Classes: 2
  Trials: 50

Best trial: 21. Best value: 0.733935: 100%|██████████| 50/50 [00:23<00:00,  2.14it/s]

  Melhor AUC (CV): 0.7339
  Tempo de tuning: 23.35s
  Melhores parâmetros: {'iterations': 381, 'learning_rate': 0.015423467501110306, 'depth': 4, 'l2_leaf_reg': 0.179334650881117, 'random_strength': 9.776707423653912, 'bagging_temperature': 0.7088451718686236, 'border_count': 57}
  Resultados salvos: optuna_results/ilpd_catboost_best.json

============================================================
RESUMO DO TUNING
============================================================
Total de datasets: 30
Tempo total de tuning: 6940.40s
AUC médio (CV): 0.8979

                             dataset  best_score    tune_time
25            analcatdata_authorship    1.000000   278.395276
4            banknote-authentication    1.000000    40.088494
24                       tic-tac-toe    1.000000    18.706865
6                        MiceProtein    0.999819   914.802143
19                               car    0.999519    22.452347
10                             vowel    0.998535   402.979586
8                            semeion    0.997293  3552.299297
9                             cnae-9    0.995036   546.307437
11                          breast-w    0.994157    15.482778
13                              wdbc    0.991388    74.933463
21                steel-plates-fault    0.968284   289.918235
2                mfeat-morphological    0.966501    99.186992
22                     balance-scale    0.953445    10.326588
0                    credit-approval    0.946419    14.668849
26  climate-model-simulation-crashes    0.943963    47.888810
14                               pc4    0.941690    63.823390
3                            vehicle    0.930060    75.901436
27                       qsar-biodeg    0.915507    41.783412
20                               kc2    0.890777    74.223497
23                               pc1    0.880341    76.316844
12                        eucalyptus    0.866198    46.161164
18                               pc3    0.861550    67.740244
7                     cylinder-bands    0.839717    40.821050
28                          diabetes    0.839521    13.903319
15                          credit-g    0.770089    24.865654
17  blood-transfusion-service-center    0.757374    13.307586
29                              ilpd    0.733935    23.346091
16                               cmc    0.727396    22.452039
1                      dresses-sales    0.657519    18.087480
5                   analcatdata_dmft    0.569998     9.227260

## Executar Treinamento

In [10]:
ensure_dirs()

# Lista completa dos 30 datasets
dataset_list = [
    # Datasets balanceados
    'credit-approval', 'dresses-sales', 'mfeat-morphological', 'vehicle',
    'banknote-authentication', 'analcatdata_dmft', 'MiceProtein', 'cylinder-bands',
    'semeion', 'cnae-9', 'vowel',
    # Datasets desbalanceados
    'breast-w', 'eucalyptus', 'wdbc', 'pc4', 'credit-g', 'cmc',
    'blood-transfusion-service-center', 'pc3', 'car', 'kc2',
    'steel-plates-fault', 'balance-scale', 'pc1', 'tic-tac-toe',
    'analcatdata_authorship', 'climate-model-simulation-crashes',
    'qsar-biodeg', 'diabetes', 'ilpd',
]

In [11]:
all_rows = []

for ds in dataset_list:
    try:
        # Verificar se os parâmetros já existem
        param_path = f"optuna_results/{ds}_catboost_best.json"
        
        if not os.path.exists(param_path):
            print(f"\n[INFO] Parâmetros não encontrados para {ds}. Executando tuning...")
            try:
                tune_catboost_optuna(ds, n_trials=50)
            except Exception as tune_err:
                print(f"[ERRO] Falha no tuning de {ds}: {tune_err}")
                continue
        
        # Treinar modelo com os melhores parâmetros
        rows = train_final_model(ds)
        all_rows.extend(rows)
        
    except FileNotFoundError as e:
        print(f"\n[ERRO] Dataset {ds} não encontrado: {e}")
        continue
    except Exception as e:
        print(f"\n[ERRO] Dataset {ds}: {e}")
        continue

============================================================
Treinando CatBoost para: credit-approval
============================================================
Melhores hiperparâmetros: {'iterations': 106, 'learning_rate': 0.06242587265091922, 'depth': 3, 'l2_leaf_reg': 0.2723574117325312, 'random_strength': 2.4057966497003065, 'bagging_temperature': 0.48431521159265845, 'border_count': 206}
  Train: 434 amostras
  Test: 207 amostras
  Features: 15
  Classes: 2
  Tempo de treino: 0.01s
  Modelo salvo: trained_models_catboost/credit-approval_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9700
    Accuracy: 0.9147
    G-Mean: 0.9155
    Cross-Entropy: 0.2493

  Resultados no TESTE:
    AUC OVO: 0.9280
    Accuracy: 0.8406
    G-Mean: 0.8420
    Cross-Entropy: 0.3475

============================================================
Treinando CatBoost para: dresses-sales
============================================================
Melhores hiperparâmetros: {'iterations': 173, 'learning_rate': 0.13614662198784633, 'depth': 7, 'l2_leaf_reg': 9.805962500133788, 'random_strength': 0.022281136225138456, 'bagging_temperature': 0.9275916119933421, 'border_count': 226}
  Train: 315 amostras
  Test: 150 amostras
  Features: 12
  Classes: 2
  Tempo de treino: 0.03s
  Modelo salvo: trained_models_catboost/dresses-sales_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9941
    Accuracy: 0.9397
    G-Mean: 0.9268
    Cross-Entropy: 0.3280

  Resultados no TESTE:
    AUC OVO: 0.5182
    Accuracy: 0.5267
    G-Mean: 0.4185
    Cross-Entropy: 0.7439

============================================================
Treinando CatBoost para: mfeat-morphological
============================================================
Melhores hiperparâmetros: {'iterations': 470, 'learning_rate': 0.09158987678281144, 'depth': 3, 'l2_leaf_reg': 1.4944578433162166, 'random_strength': 0.6448181736799103, 'bagging_temperature': 0.8612108645740625, 'border_count': 63}
  Train: 1260 amostras
  Test: 600 amostras
  Features: 6
  Classes: 10
  Tempo de treino: 0.20s
  Modelo salvo: trained_models_catboost/mfeat-morphological_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9879
    Accuracy: 0.8381
    G-Mean: 0.8151
    Cross-Entropy: 0.4057

  Resultados no TESTE:
    AUC OVO: 0.9633
    Accuracy: 0.7100
    G-Mean: 0.6450
    Cross-Entropy: 0.6419

============================================================
Treinando CatBoost para: vehicle
============================================================
Melhores hiperparâmetros: {'iterations': 229, 'learning_rate': 0.08749994766488771, 'depth': 3, 'l2_leaf_reg': 2.50507677759741, 'random_strength': 0.002775962905365263, 'bagging_temperature': 0.9982835861660032, 'border_count': 47}
  Train: 532 amostras
  Test: 254 amostras
  Features: 18
  Classes: 4
  Tempo de treino: 0.04s
  Modelo salvo: trained_models_catboost/vehicle_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9926
    Accuracy: 0.9417
    G-Mean: 0.9406
    Cross-Entropy: 0.3350

  Resultados no TESTE:
    AUC OVO: 0.9409
    Accuracy: 0.7953
    G-Mean: 0.7617
    Cross-Entropy: 0.4768

============================================================
Treinando CatBoost para: banknote-authentication
============================================================
Melhores hiperparâmetros: {'iterations': 440, 'learning_rate': 0.07725378389307355, 'depth': 8, 'l2_leaf_reg': 0.011527987128232402, 'random_strength': 7.579479953348009, 'bagging_temperature': 0.8324426408004217, 'border_count': 79}
  Train: 864 amostras
  Test: 412 amostras
  Features: 4
  Classes: 2
  Tempo de treino: 0.23s
  Modelo salvo: trained_models_catboost/banknote-authentication_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0001

  Resultados no TESTE:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0004

============================================================
Treinando CatBoost para: analcatdata_dmft
============================================================
Melhores hiperparâmetros: {'iterations': 226, 'learning_rate': 0.02581683081395819, 'depth': 3, 'l2_leaf_reg': 0.03456218301910605, 'random_strength': 6.2818179408717825, 'bagging_temperature': 0.06512629831562661, 'border_count': 112}
  Train: 415 amostras
  Test: 199 amostras
  Features: 4
  Classes: 5
  Tempo de treino: 0.03s
  Modelo salvo: trained_models_catboost/analcatdata_dmft_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.7372
    Accuracy: 0.3880
    G-Mean: 0.3607
    Cross-Entropy: 1.4080

  Resultados no TESTE:
    AUC OVO: 0.5894
    Accuracy: 0.2111
    G-Mean: 0.2009
    Cross-Entropy: 1.6044

============================================================
Treinando CatBoost para: MiceProtein
============================================================
Melhores hiperparâmetros: {'iterations': 463, 'learning_rate': 0.17431776476826738, 'depth': 6, 'l2_leaf_reg': 0.1543762310283612, 'random_strength': 0.017333962988524784, 'bagging_temperature': 0.0002621123047130136, 'border_count': 130}
  Train: 680 amostras
  Test: 324 amostras
  Features: 77
  Classes: 8
  Tempo de treino: 2.78s
  Modelo salvo: trained_models_catboost/MiceProtein_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0005

  Resultados no TESTE:
    AUC OVO: 0.9999
    Accuracy: 0.9815
    G-Mean: 0.9752
    Cross-Entropy: 0.0581

============================================================
Treinando CatBoost para: cylinder-bands
============================================================
Melhores hiperparâmetros: {'iterations': 433, 'learning_rate': 0.023233935695385823, 'depth': 5, 'l2_leaf_reg': 0.01573559367415984, 'random_strength': 5.1654756974786284, 'bagging_temperature': 0.3099191723207154, 'border_count': 34}
  Train: 340 amostras
  Test: 162 amostras
  Features: 37
  Classes: 2
  Tempo de treino: 0.13s
  Modelo salvo: trained_models_catboost/cylinder-bands_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0525

  Resultados no TESTE:
    AUC OVO: 0.8999
    Accuracy: 0.8148
    G-Mean: 0.7843
    Cross-Entropy: 0.3960

============================================================
Treinando CatBoost para: semeion
============================================================
Melhores hiperparâmetros: {'iterations': 433, 'learning_rate': 0.09109634495981846, 'depth': 4, 'l2_leaf_reg': 0.06283219021952564, 'random_strength': 0.006190558077203713, 'bagging_temperature': 0.03198201865774064, 'border_count': 32}
  Train: 1003 amostras
  Test: 478 amostras
  Features: 256
  Classes: 10
  Tempo de treino: 2.56s
  Modelo salvo: trained_models_catboost/semeion_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0018

  Resultados no TESTE:
    AUC OVO: 0.9982
    Accuracy: 0.9351
    G-Mean: 0.9354
    Cross-Entropy: 0.1944

============================================================
Treinando CatBoost para: cnae-9
============================================================
Melhores hiperparâmetros: {'iterations': 452, 'learning_rate': 0.040359456141514524, 'depth': 10, 'l2_leaf_reg': 0.06035601781783563, 'random_strength': 3.2092601977965796, 'bagging_temperature': 0.838845022048059, 'border_count': 201}
  Train: 680 amostras
  Test: 324 amostras
  Features: 856
  Classes: 9
  Tempo de treino: 32.08s
  Modelo salvo: trained_models_catboost/cnae-9_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 0.9971
    G-Mean: 0.9972
    Cross-Entropy: 0.0907

  Resultados no TESTE:
    AUC OVO: 0.9955
    Accuracy: 0.9259
    G-Mean: 0.9246
    Cross-Entropy: 0.2987

============================================================
Treinando CatBoost para: vowel
============================================================
Melhores hiperparâmetros: {'iterations': 440, 'learning_rate': 0.07725378389307355, 'depth': 8, 'l2_leaf_reg': 0.011527987128232402, 'random_strength': 7.579479953348009, 'bagging_temperature': 0.8324426408004217, 'border_count': 79}
  Train: 623 amostras
  Test: 297 amostras
  Features: 12
  Classes: 11
  Tempo de treino: 1.50s
  Modelo salvo: trained_models_catboost/vowel_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0003

  Resultados no TESTE:
    AUC OVO: 0.9998
    Accuracy: 0.9495
    G-Mean: 0.9543
    Cross-Entropy: 0.0982

============================================================
Treinando CatBoost para: breast-w
============================================================
Melhores hiperparâmetros: {'iterations': 473, 'learning_rate': 0.023596041097921166, 'depth': 3, 'l2_leaf_reg': 0.38472443810911483, 'random_strength': 1.8308510115244405, 'bagging_temperature': 0.29850342982695705, 'border_count': 62}
  Train: 440 amostras
  Test: 210 amostras
  Features: 9
  Classes: 2
  Tempo de treino: 0.08s
  Modelo salvo: trained_models_catboost/breast-w_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0107

  Resultados no TESTE:
    AUC OVO: 0.9975
    Accuracy: 0.9667
    G-Mean: 0.9595
    Cross-Entropy: 0.0612

============================================================
Treinando CatBoost para: eucalyptus
============================================================
Melhores hiperparâmetros: {'iterations': 337, 'learning_rate': 0.04577423662995581, 'depth': 5, 'l2_leaf_reg': 3.445991322357863, 'random_strength': 2.734435746603416, 'bagging_temperature': 0.22316076445423746, 'border_count': 91}
  Train: 350 amostras
  Test: 167 amostras
  Features: 19
  Classes: 4
  Tempo de treino: 0.14s
  Modelo salvo: trained_models_catboost/eucalyptus_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9954
    Accuracy: 0.9343
    G-Mean: 0.9217
    Cross-Entropy: 0.3809

  Resultados no TESTE:
    AUC OVO: 0.8794
    Accuracy: 0.6587
    G-Mean: 0.5919
    Cross-Entropy: 0.7828

============================================================
Treinando CatBoost para: wdbc
============================================================
Melhores hiperparâmetros: {'iterations': 197, 'learning_rate': 0.022194461001238907, 'depth': 8, 'l2_leaf_reg': 0.025506553470523986, 'random_strength': 5.137597547919509, 'bagging_temperature': 0.3107158525298094, 'border_count': 243}
  Train: 358 amostras
  Test: 171 amostras
  Features: 30
  Classes: 2
  Tempo de treino: 0.56s
  Modelo salvo: trained_models_catboost/wdbc_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0014

  Resultados no TESTE:
    AUC OVO: 0.9979
    Accuracy: 0.9766
    G-Mean: 0.9714
    Cross-Entropy: 0.0543

============================================================
Treinando CatBoost para: pc4
============================================================
Melhores hiperparâmetros: {'iterations': 220, 'learning_rate': 0.019195790953683137, 'depth': 7, 'l2_leaf_reg': 1.2192877487916944, 'random_strength': 0.03833083258575718, 'bagging_temperature': 0.2840087086504303, 'border_count': 34}
  Train: 918 amostras
  Test: 438 amostras
  Features: 37
  Classes: 2
  Tempo de treino: 0.13s
  Modelo salvo: trained_models_catboost/pc4_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 0.9967
    G-Mean: 0.9861
    Cross-Entropy: 0.0504

  Resultados no TESTE:
    AUC OVO: 0.9421
    Accuracy: 0.9018
    G-Mean: 0.5791
    Cross-Entropy: 0.2088

============================================================
Treinando CatBoost para: credit-g
============================================================
Melhores hiperparâmetros: {'iterations': 284, 'learning_rate': 0.03082519278153801, 'depth': 6, 'l2_leaf_reg': 4.632954876006153, 'random_strength': 6.515438729889783, 'bagging_temperature': 0.8205248119201679, 'border_count': 46}
  Train: 630 amostras
  Test: 300 amostras
  Features: 20
  Classes: 2
  Tempo de treino: 0.09s
  Modelo salvo: trained_models_catboost/credit-g_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9877
    Accuracy: 0.9476
    G-Mean: 0.9122
    Cross-Entropy: 0.2679

  Resultados no TESTE:
    AUC OVO: 0.7869
    Accuracy: 0.7700
    G-Mean: 0.6006
    Cross-Entropy: 0.4968

============================================================
Treinando CatBoost para: cmc
============================================================
Melhores hiperparâmetros: {'iterations': 464, 'learning_rate': 0.015144096298459114, 'depth': 4, 'l2_leaf_reg': 9.864098940130239, 'random_strength': 0.01883520641442139, 'bagging_temperature': 0.2282974055610772, 'border_count': 165}
  Train: 927 amostras
  Test: 442 amostras
  Features: 9
  Classes: 3
  Tempo de treino: 0.12s
  Modelo salvo: trained_models_catboost/cmc_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.7897
    Accuracy: 0.5965
    G-Mean: 0.5615
    Cross-Entropy: 0.8461

  Resultados no TESTE:
    AUC OVO: 0.7615
    Accuracy: 0.5656
    G-Mean: 0.5170
    Cross-Entropy: 0.8768

============================================================
Treinando CatBoost para: blood-transfusion-service-center
============================================================
Melhores hiperparâmetros: {'iterations': 186, 'learning_rate': 0.0241090156225405, 'depth': 3, 'l2_leaf_reg': 0.7906565859118585, 'random_strength': 4.9621912184240005, 'bagging_temperature': 0.701770768490543, 'border_count': 97}
  Train: 470 amostras
  Test: 225 amostras
  Features: 4
  Classes: 2
  Tempo de treino: 0.01s
  Modelo salvo: trained_models_catboost/blood-transfusion-service-center_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.7866
    Accuracy: 0.7957
    G-Mean: 0.3940
    Cross-Entropy: 0.4455

  Resultados no TESTE:
    AUC OVO: 0.7407
    Accuracy: 0.7378
    G-Mean: 0.2852
    Cross-Entropy: 0.5126

============================================================
Treinando CatBoost para: pc3
============================================================
Melhores hiperparâmetros: {'iterations': 358, 'learning_rate': 0.01018158968177659, 'depth': 5, 'l2_leaf_reg': 0.012748802652224488, 'random_strength': 0.03031020779895982, 'bagging_temperature': 0.8841734109557197, 'border_count': 239}
  Train: 984 amostras
  Test: 469 amostras
  Features: 37
  Classes: 2
  Tempo de treino: 0.19s
  Modelo salvo: trained_models_catboost/pc3_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9980
    Accuracy: 0.9787
    G-Mean: 0.8852
    Cross-Entropy: 0.0765

  Resultados no TESTE:
    AUC OVO: 0.8067
    Accuracy: 0.8827
    G-Mean: 0.3721
    Cross-Entropy: 0.2961

============================================================
Treinando CatBoost para: car
============================================================
Melhores hiperparâmetros: {'iterations': 182, 'learning_rate': 0.06931052352438204, 'depth': 6, 'l2_leaf_reg': 0.014987093363755994, 'random_strength': 0.0010354844596193377, 'bagging_temperature': 0.18764823680388093, 'border_count': 168}
  Train: 1088 amostras
  Test: 519 amostras
  Features: 6
  Classes: 4
  Tempo de treino: 0.06s
  Modelo salvo: trained_models_catboost/car_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0181

  Resultados no TESTE:
    AUC OVO: 0.9998
    Accuracy: 0.9904
    G-Mean: 0.9892
    Cross-Entropy: 0.0439

============================================================
Treinando CatBoost para: kc2
============================================================
Melhores hiperparâmetros: {'iterations': 336, 'learning_rate': 0.024725432634456045, 'depth': 3, 'l2_leaf_reg': 3.5287603689687526, 'random_strength': 0.016280202637738, 'bagging_temperature': 0.8932078456752282, 'border_count': 243}
  Train: 328 amostras
  Test: 157 amostras
  Features: 21
  Classes: 2
  Tempo de treino: 0.08s
  Modelo salvo: trained_models_catboost/kc2_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9797
    Accuracy: 0.9726
    G-Mean: 0.9354
    Cross-Entropy: 0.1418

  Resultados no TESTE:
    AUC OVO: 0.7636
    Accuracy: 0.7898
    G-Mean: 0.6279
    Cross-Entropy: 0.4798

============================================================
Treinando CatBoost para: steel-plates-fault
============================================================
Melhores hiperparâmetros: {'iterations': 482, 'learning_rate': 0.11389744687452437, 'depth': 6, 'l2_leaf_reg': 2.0372703602990074, 'random_strength': 1.7713868448871888, 'bagging_temperature': 0.1848987975553109, 'border_count': 58}
  Train: 1222 amostras
  Test: 583 amostras
  Features: 27
  Classes: 7
  Tempo de treino: 0.61s
  Modelo salvo: trained_models_catboost/steel-plates-fault_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 0.9992
    G-Mean: 0.9996
    Cross-Entropy: 0.0553

  Resultados no TESTE:
    AUC OVO: 0.9706
    Accuracy: 0.7976
    G-Mean: 0.7937
    Cross-Entropy: 0.4954

============================================================
Treinando CatBoost para: balance-scale
============================================================
Melhores hiperparâmetros: {'iterations': 363, 'learning_rate': 0.19002893624554873, 'depth': 4, 'l2_leaf_reg': 0.7875595671132296, 'random_strength': 0.007826811222696904, 'bagging_temperature': 0.3356874421657183, 'border_count': 119}
  Train: 393 amostras
  Test: 188 amostras
  Features: 4
  Classes: 3
  Tempo de treino: 0.04s
  Modelo salvo: trained_models_catboost/balance-scale_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0161

  Resultados no TESTE:
    AUC OVO: 0.9494
    Accuracy: 0.8883
    G-Mean: 0.5378
    Cross-Entropy: 0.3003

============================================================
Treinando CatBoost para: pc1
============================================================
Melhores hiperparâmetros: {'iterations': 174, 'learning_rate': 0.07934237918397923, 'depth': 10, 'l2_leaf_reg': 4.860114156580749, 'random_strength': 0.7329821378866582, 'bagging_temperature': 0.6826182661984666, 'border_count': 178}
  Train: 698 amostras
  Test: 333 amostras
  Features: 21
  Classes: 2
  Tempo de treino: 0.57s
  Modelo salvo: trained_models_catboost/pc1_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 0.9998
    Accuracy: 0.9943
    G-Mean: 0.9555
    Cross-Entropy: 0.0311

  Resultados no TESTE:
    AUC OVO: 0.8727
    Accuracy: 0.9189
    G-Mean: 0.3317
    Cross-Entropy: 0.2239

============================================================
Treinando CatBoost para: tic-tac-toe
============================================================
Melhores hiperparâmetros: {'iterations': 343, 'learning_rate': 0.13999834028477615, 'depth': 6, 'l2_leaf_reg': 0.1214423851252321, 'random_strength': 0.29968948789610234, 'bagging_temperature': 0.7066027851795458, 'border_count': 195}
  Train: 603 amostras
  Test: 288 amostras
  Features: 9
  Classes: 2
  Tempo de treino: 0.08s
  Modelo salvo: trained_models_catboost/tic-tac-toe_catboost.cbm

  Resultados no TREINO:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0010

  Resultados no TESTE:
    AUC OVO: 1.0000
    Accuracy: 1.0000
    G-Mean: 1.0000
    Cross-Entropy: 0.0114

============================================================
Treinando CatBoost para: analcatdata_authorship
============================================================
Melhores hiperparâmetros: {'iterations': 461, 'learning_rate': 0.037138849888776686, 'depth': 9, 'l2_leaf_reg': 0.012516946208041318, 'random_strength': 7.697180747899158, 'bagging_temperature': 0.9961602315751977, 'border_count': 34}
  Train: 529 amostras
  Test: 253 amostras
  Features: 70
  Classes: 4
  Tempo de treino: 1.57s
  Modelo salvo: trained_models_catboost/analcatdata_authorship_catboost.cbm

  Resultados no TREINO:

## Salvar e Visualizar Resultados

In [12]:
if len(all_rows) > 0:
    df_results = pd.DataFrame(all_rows)
    output_path = "results/final_catboost_results.csv"
    df_results.to_csv(output_path, index=False)
    print(f"Resultados salvos em: {output_path}")
else:
    print("Nenhum resultado para salvar.")

Resultados salvos em: results/final_catboost_results.csv

In [13]:
# Exibir DataFrame completo
if len(all_rows) > 0:
    display(df_results)

,split,nome_modelo,dataset,tempo_tune,tempo_train,auc_ovo,mean_acc,g_mean,mean_cross_entropy,tempo_predict
0,train,CatBoost,credit-approval,14.668849,0.014622,0.970018,0.914747,0.915469,0.249339,0.000187
1,test,CatBoost,credit-approval,14.668849,0.014622,0.928022,0.840580,0.842020,0.347480,0.000108
2,train,CatBoost,dresses-sales,18.087480,0.027985,0.994103,0.939683,0.926759,0.328006,0.000168
3,test,CatBoost,dresses-sales,18.087480,0.027985,0.518154,0.526667,0.418510,0.743947,0.000110
4,train,CatBoost,mfeat-morphological,99.186992,0.203404,0.987884,0.838095,0.815146,0.405665,0.000584
5,test,CatBoost,mfeat-morphological,99.186992,0.203404,0.963341,0.710000,0.645019,0.641938,0.000773
6,train,CatBoost,vehicle,75.901436,0.041750,0.992620,0.941729,0.940630,0.334969,0.000295
7,test,CatBoost,vehicle,75.901436,0.041750,0.940860,0.795276,0.761709,0.476767,0.000184
8,train,CatBoost,banknote-authentication,40.088494,0.233166,1.000000,1.000000,1.000000,0.000086,0.000474
9,test,CatBoost,banknote-authentication,40.088494,0.233166,1.000000,1.000000,1.000000,0.000357,0.000277
10,train,CatBoost,analcatdata_dmft,9.227260,0.027596,0.737152,0.387952,0.360693,1.408023,0.000233
11,test,CatBoost,analcatdata_dmft,9.227260,0.027596,0.589355,0.211055,0.200886,1.604429,0.000144
12,train,CatBoost,MiceProtein,914.802143,2.781073,1.000000,1.000000,1.000000,0.000483,0.000559
13,test,CatBoost,MiceProtein,914.802143,2.781073,0.999932,0.981481,0.975228,0.058066,0.000506
14,train,CatBoost,cylinder-bands,40.821050,0.127134,1.000000,1.000000,1.000000,0.052537,0.000289
15,test,CatBoost,cylinder-bands,40.821050,0.127134,0.899921,0.814815,0.784272,0.396048,0.000162
16,train,CatBoost,semeion,3552.299297,2.561040,1.000000,1.000000,1.000000,0.001753,0.000953
17,test,CatBoost,semeion,3552.299297,2.561040,0.998175,0.935146,0.935406,0.194377,0.000828
18,train,CatBoost,cnae-9,546.307437,32.078905,0.999984,0.997059,0.997173,0.090731,0.001821
19,test,CatBoost,cnae-9,546.307437,32.078905,0.995481,0.925926,0.924648,0.298727,0.001301
20,train,CatBoost,vowel,402.979586,1.499479,1.000000,1.000000,1.000000,0.000344,0.000959
21,test,CatBoost,vowel,402.979586,1.499479,0.999784,0.949495,0.954293,0.098170,0.000828
22,train,CatBoost,breast-w,15.482778,0.082564,1.000000,1.000000,1.000000,0.010676,0.000265
23,test,CatBoost,breast-w,15.482778,0.082564,0.997495,0.966667,0.959464,0.061169,0.000141
24,train,CatBoost,eucalyptus,46.161164,0.142004,0.995437,0.934286,0.921681,0.380877,0.000503
25,test,CatBoost,eucalyptus,46.161164,0.142004,0.879355,0.658683,0.591851,0.782796,0.000725
26,train,CatBoost,wdbc,74.933463,0.560814,1.000000,1.000000,1.000000,0.001443,0.000386
27,test,CatBoost,wdbc,74.933463,0.560814,0.997942,0.976608,0.971372,0.054264,0.000194
28,train,CatBoost,pc4,63.823390,0.133887,0.999983,0.996732,0.986143,0.050399,0.000493
29,test,CatBoost,pc4,63.823390,0.133887,0.942087,0.901826,0.579142,0.208806,0.000227
30,train,CatBoost,credit-g,24.865654,0.085177,0.987654,0.947619,0.912243,0.267941,0.000329
31,test,CatBoost,credit-g,24.865654,0.085177,0.786950,0.770000,0.600576,0.496768,0.000186
32,train,CatBoost,cmc,22.452039,0.119765,0.789748,0.596548,0.561542,0.846062,0.000429
33,test,CatBoost,cmc,22.452039,0.119765,0.761496,0.565611,0.517027,0.876830,0.000371
34,train,CatBoost,blood-transfusion-service-center,13.307586,0.014281,0.786602,0.795745,0.393997,0.445540,0.000197
35,test,CatBoost,blood-transfusion-service-center,13.307586,0.014281,0.740657,0.737778,0.285155,0.512587,0.000122
36,train,CatBoost,pc3,67.740244,0.193985,0.998036,0.978659,0.885158,0.076464,0.000363
37,test,CatBoost,pc3,67.740244,0.193985,0.806657,0.882729,0.372069,0.296066,0.000252
38,train,CatBoost,car,22.452347,0.061990,1.000000,1.000000,1.000000,0.018102,0.000502
39,test,CatBoost,car,22.452347,0.061990,0.999778,0.990366,0.989234,0.043932,0.000304
40,train,CatBoost,kc2,74.223497,0.084872,0.979655,0.972561,0.935414,0.141757,0.000243
41,test,CatBoost,kc2,74.223497,0.084872,0.763569,0.789809,0.627905,0.479826,0.000146
42,train,CatBoost,steel-plates-fault,289.918235,0.609300,1.000000,0.999182,0.999649,0.055326,0.000706
43,test,CatBoost,steel-plates-fault,289.918235,0.609300,0.970594,0.797599,0.793732,0.495395,0.000650
44,train,CatBoost,balance-scale,10.326588,0.041568,1.000000,1.000000,1.000000,0.016107,0.000318
45,test,CatBoost,balance-scale,10.326588,0.041568,0.949401,0.888298,0.537810,0.300272,0.000174
46,train,CatBoost,pc1,76.316844,0.566587,0.999783,0.994269,0.955533,0.031143,0.000430
47,test,CatBoost,pc1,76.316844,0.566587,0.872731,0.918919,0.331695,0.223936,0.000209
48,train,CatBoost,tic-tac-toe,18.706865,0.075687,1.000000,1.000000,1.000000,0.001021,0.000611
49,test,CatBoost,tic-tac-toe,18.706865,0.075687,1.000000,1.000000,1.000000,0.011374,0.000431
50,train,CatBoost,analcatdata_authorship,278.395276,1.568352,1.000000,1.000000,1.000000,0.000243,0.000928
51,test,CatBoost,analcatdata_authorship,278.395276,1.568352,0.999305,0.992095,0.981219,0.039678,0.000581
52,train,CatBoost,climate-model-simulation-crashes,47.888810,0.038378,1.000000,0.994118,0.963624,0.192669,0.000189
53,test,CatBoost,climate-model-simulation-crashes,47.888810,0.038378,0.964286,0.913580,0.000000,0.281015,0.000140
54,train,CatBoost,qsar-biodeg,41.783412,0.191179,0.995242,0.965361,0.959770,0.144859,0.000479
55,test,CatBoost,qsar-biodeg,41.783412,0.191179,0.936204,0.883281,0.875362,0.302931,0.000248
56,train,CatBoost,diabetes,13.903319,0.024043,0.922983,0.842650,0.789063,0.389855,0.000188
57,test,CatBoost,diabetes,13.903319,0.024043,0.803477,0.753247,0.688121,0.506561,0.000109
58,train,CatBoost,ilpd,23.346091,0.075555,0.913086,0.828338,0.656816,0.396706,0.000247
59,test,CatBoost,ilpd,23.346091,0.075555,0.777427,0.708571,0.368967,0.468795,0.000155

### Resultados no Teste

In [14]:
if len(all_rows) > 0:
    test_results = df_results[df_results["split"] == "test"][
        ["dataset", "auc_ovo", "mean_acc", "g_mean", "mean_cross_entropy"]
    ].copy()
    test_results = test_results.sort_values("auc_ovo", ascending=False)
    display(test_results)

,dataset,auc_ovo,mean_acc,g_mean,mean_cross_entropy
9,banknote-authentication,1.000000,1.000000,1.000000,0.000357
49,tic-tac-toe,1.000000,1.000000,1.000000,0.011374
13,MiceProtein,0.999932,0.981481,0.975228,0.058066
21,vowel,0.999784,0.949495,0.954293,0.098170
39,car,0.999778,0.990366,0.989234,0.043932
51,analcatdata_authorship,0.999305,0.992095,0.981219,0.039678
17,semeion,0.998175,0.935146,0.935406,0.194377
27,wdbc,0.997942,0.976608,0.971372,0.054264
23,breast-w,0.997495,0.966667,0.959464,0.061169
19,cnae-9,0.995481,0.925926,0.924648,0.298727
43,steel-plates-fault,0.970594,0.797599,0.793732,0.495395
53,climate-model-simulation-crashes,0.964286,0.913580,0.000000,0.281015
5,mfeat-morphological,0.963341,0.710000,0.645019,0.641938
45,balance-scale,0.949401,0.888298,0.537810,0.300272
29,pc4,0.942087,0.901826,0.579142,0.208806
7,vehicle,0.940860,0.795276,0.761709,0.476767
55,qsar-biodeg,0.936204,0.883281,0.875362,0.302931
1,credit-approval,0.928022,0.840580,0.842020,0.347480
15,cylinder-bands,0.899921,0.814815,0.784272,0.396048
25,eucalyptus,0.879355,0.658683,0.591851,0.782796
47,pc1,0.872731,0.918919,0.331695,0.223936
37,pc3,0.806657,0.882729,0.372069,0.296066
57,diabetes,0.803477,0.753247,0.688121,0.506561
31,credit-g,0.786950,0.770000,0.600576,0.496768
59,ilpd,0.777427,0.708571,0.368967,0.468795
41,kc2,0.763569,0.789809,0.627905,0.479826
33,cmc,0.761496,0.565611,0.517027,0.876830
35,blood-transfusion-service-center,0.740657,0.737778,0.285155,0.512587
11,analcatdata_dmft,0.589355,0.211055,0.200886,1.604429
3,dresses-sales,0.518154,0.526667,0.418510,0.743947

### Estatísticas Resumidas

In [15]:
if len(all_rows) > 0:
    print("Estatísticas dos resultados no TESTE:")
    print("="*50)
    test_only = df_results[df_results["split"] == "test"]
    
    metrics = ["auc_ovo", "mean_acc", "g_mean", "mean_cross_entropy"]
    
    for m in metrics:
        print(f"\n{m}:")
        print(f"  Média: {test_only[m].mean():.4f}")
        print(f"  Desvio Padrão: {test_only[m].std():.4f}")
        print(f"  Mínimo: {test_only[m].min():.4f}")
        print(f"  Máximo: {test_only[m].max():.4f}")

Estatísticas dos resultados no TESTE:
==================================================

auc_ovo:
  Média: 0.8927
  Desvio Padrão: 0.1273
  Mínimo: 0.5182
  Máximo: 1.0000

mean_acc:
  Média: 0.8262
  Desvio Padrão: 0.1724
  Mínimo: 0.2111
  Máximo: 1.0000

g_mean:
  Média: 0.6838
  Desvio Padrão: 0.2779
  Mínimo: 0.0000
  Máximo: 1.0000

mean_cross_entropy:
  Média: 0.3768
  Desvio Padrão: 0.3333
  Mínimo: 0.0004
  Máximo: 1.6044

### Tempos de Execução

In [16]:
if len(all_rows) > 0:
    print("Tempos de Execução:")
    print("="*50)
    
    # Pegar apenas uma linha por dataset (treino e teste têm os mesmos tempos)
    tempo_df = df_results[df_results["split"] == "test"][["dataset", "tempo_tune", "tempo_train", "tempo_predict"]]
    
    print(f"\nTempo total de tuning: {tempo_df['tempo_tune'].sum():.2f}s")
    print(f"Tempo total de treino: {tempo_df['tempo_train'].sum():.2f}s")
    print(f"Tempo médio de predição: {tempo_df['tempo_predict'].mean():.4f}s")
    
    display(tempo_df)

Tempos de Execução:
==================================================

Tempo total de tuning: 6940.40s
Tempo total de treino: 44.27s
Tempo médio de predição: 0.0004s

                             dataset   tempo_tune  tempo_train  tempo_predict
1                    credit-approval    14.668849     0.014622       0.000108
3                      dresses-sales    18.087480     0.027985       0.000110
5                mfeat-morphological    99.186992     0.203404       0.000773
7                            vehicle    75.901436     0.041750       0.000184
9            banknote-authentication    40.088494     0.233166       0.000277
11                  analcatdata_dmft     9.227260     0.027596       0.000144
13                       MiceProtein   914.802143     2.781073       0.000506
15                    cylinder-bands    40.821050     0.127134       0.000162
17                           semeion  3552.299297     2.561040       0.000828
19                            cnae-9   546.307437    32.078905       0.001301
21                             vowel   402.979586     1.499479       0.000828
23                          breast-w    15.482778     0.082564       0.000141
25                        eucalyptus    46.161164     0.142004       0.000725
27                              wdbc    74.933463     0.560814       0.000194
29                               pc4    63.823390     0.133887       0.000227
31                          credit-g    24.865654     0.085177       0.000186
33                               cmc    22.452039     0.119765       0.000371
35  blood-transfusion-service-center    13.307586     0.014281       0.000122
37                               pc3    67.740244     0.193985       0.000252
39                               car    22.452347     0.061990       0.000304
41                               kc2    74.223497     0.084872       0.000146
43                steel-plates-fault   289.918235     0.609300       0.000650
45                     balance-scale    10.326588     0.041568       0.000174
47                               pc1    76.316844     0.566587       0.000209
49                       tic-tac-toe    18.706865     0.075687       0.000431
51            analcatdata_authorship   278.395276     1.568352       0.000581
53  climate-model-simulation-crashes    47.888810     0.038378       0.000140
55                       qsar-biodeg    41.783412     0.191179       0.000248
57                          diabetes    13.903319     0.024043       0.000109
59                              ilpd    23.346091     0.075555       0.000155